export const DEFAULT_CLICK_TRANSPORT_TIMEOUT_MS = 60_000;
export const DEFAULT_DIALOG_TRANSPORT_TIMEOUT_MS = 30_000;
export const DEFAULT_TARGET_CREATION_TRANSPORT_TIMEOUT_MS = 30_000;
export const DEFAULT_SNAPSHOT_TRANSPORT_TIMEOUT_MS = 30_000;
export const DEFAULT_REVIEW_TRANSPORT_TIMEOUT_MS = 30_000;
export const DEFAULT_SCREENSHOT_TRANSPORT_TIMEOUT_MS = 30_000;
export const DEFAULT_WORKFLOW_TRANSPORT_TIMEOUT_MS = 120_000;
