import type { BrowserManager } from "./browser-manager";

export type BrowserManagerLike = Pick<BrowserManager,
  | "launch"
  | "connect"
  | "connectRelay"
  | "disconnect"
  | "status"
  | "goto"
  | "waitForLoad"
  | "waitForRef"
  | "snapshot"
  | "click"
  | "type"
  | "select"
  | "scroll"
  | "domGetHtml"
  | "domGetText"
  | "clonePage"
  | "cloneComponent"
  | "perfMetrics"
  | "screenshot"
  | "consolePoll"
  | "networkPoll"
  | "listPages"
  | "page"
  | "closePage"
  | "listTargets"
  | "useTarget"
  | "newTarget"
  | "closeTarget"
>;
